# Generated by Django 3.2.8 on 2022-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon', models.CharField(max_length=64)),
                ('url_path', models.CharField(max_length=128, verbose_name='url_path')),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
