# Generated by Django 3.2.8 on 2022-08-09 11:52

from django.db import migrations


def create_data(apps, schema_editor):
    Menu = apps.get_model('Menu', 'Menu')
    Menu(name="Home", icon="fa-home", url_path="/", parent_id=0).save()

class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
